### ISSUE TITLE
Install Flutter Version Manager does not replace flutter path

### ISSUE THREAD

**Issue by talp-flytrex** [infinum/Install-Flutter-Version-Manager-Bitrise#2]
When using this step on a project with flutter version `3.7.11` in `fvm_config.json`, the Flutter Build step still uses the latest flutter version `3.10.1`.

Path after `Install Flutter Version Manager` step:
```
/Users/vagrant/fvm/versions/3.7.11/bin:/root/flutter-sdk/flutter/bin:/root/flutter-sdk/flutter/bin/cache/dart-sdk/bin:/root/flutter-sdk/flutter/.pub-cache/bin:/root/.pub-cache/bin:/root/.bitrise/tools:/root/.asdf/shims:/root/.asdf/bin:/opt/flutter/bin:/usr/local/bin/kotlinc/bin:/bitrise/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin:/opt/android-sdk-linux/platform-tools:/opt/android-sdk-linux/cmdline-tools/latest/bin:/opt/android-sdk-linux/cmdline-tools/7.0/bin:/opt/gradle/gradle-8.0.2/bin/:/opt/android-sdk-linux/ndk-bundle
```

Output of `flutter doctor` after `Install Flutter Version Manager` step:
```
[✓] Flutter (Channel stable, 3.10.1, on Ubuntu 20.04.6 LTS 5.13.0-1015-gcp, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] Connected device (1 available)
[✓] Network resources
```

The following `Flutter Build` step wrongly uses flutter `3.10.1` as well.

**Comment by itsJoKr** [comment]
@talp-flytrex can you share the whole workflow with us?

**Comment by talp-flytrex** [comment]
@itsJoKr 
Of course:
```
---
format_version: '11'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: flutter
trigger_map:
- push_branch: deploy
workflows:
  test:
    steps:
    - activate-ssh-key@4:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@8: {}
    - get-pubspec-version-and-build-number@1: {}
    - install-flutter-version-manager@1: {}
    - flutter-installer@0:
        run_if: ''
    - script@1:
        inputs:
        - is_debug: 'yes'
        - content: fvm flutter doctor
        run_if: 'false'
    - script@1:
        inputs:
        - content: flutter doctor
    meta:
      bitrise.io:
        stack: linux-docker-android-20.04
        machine_type_id: standard
```
